// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddToQueue'](arg1, arg2, arg3);
}

export function AmIRunningOnMacos() {
  return window['go']['main']['App']['AmIRunningOnMacos']();
}

export function CancelTransfer(arg1, arg2, arg3) {
  return window['go']['main']['App']['CancelTransfer'](arg1, arg2, arg3);
}

export function DownloadTransfer(arg1, arg2) {
  return window['go']['main']['App']['DownloadTransfer'](arg1, arg2);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetDirectoryContent(arg1) {
  return window['go']['main']['App']['GetDirectoryContent'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetIp() {
  return window['go']['main']['App']['GetIp']();
}

export function GetKey() {
  return window['go']['main']['App']['GetKey']();
}

export function GetPendingDownloads() {
  return window['go']['main']['App']['GetPendingDownloads']();
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}
