// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetDirectoryContent(arg1) {
  return window['go']['main']['App']['GetDirectoryContent'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetIp() {
  return window['go']['main']['App']['GetIp']();
}

export function GetKey() {
  return window['go']['main']['App']['GetKey']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
