// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {database} from '../models';

export function AddToQueue(arg1:Array<main.File>,arg2:string,arg3:string):Promise<void>;

export function AmIRunningOnMacos():Promise<boolean>;

export function CancelTransfer(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GetDevices():Promise<Array<string>>;

export function GetDirectoryContent(arg1:string):Promise<Array<main.File>>;

export function GetHomeDir():Promise<string>;

export function GetIp():Promise<string>;

export function GetKey():Promise<string>;

export function GetTransfers():Promise<Array<database.Transfer>>;
