// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDevices():Promise<Array<string>>;

export function GetKey():Promise<string>;

export function Greet(arg1:string):Promise<string>;
